- hosts: all
  become: true
  tasks:
    - name: update OS
      become: true
      command: yum update -y
    - name: install python3
      yum:
        name: python3
        state: latest
    - name: install python-devel
      yum:
        name: python-devel
        state: latest
    - name: install zlib-devel
      yum:
        name: zlib-devel
        state: latest
    - name: install libjpeg
      yum:
        name: libjpeg-turbo-devel
        state: latest
    - name: install gcc
      yum:
        name: gcc
        state: latest
    - name: install git
      yum:
        name: git
        state: latest
    - name: install go
      yum:
        name: go
        state: latest
    - name: install tmux
      yum:
        name: tmux
        state: latest
